#!/usr/bin/ruby
require 'fileutils'

vender_path = "./project/vendor"
libs_on_github = [
    "git://github.com/katsuyoshi/cider.git",
    "git://github.com/sazameki/json-objc-parser.git"
]

FileUtils.mkdir_p vender_path

Dir.chdir vender_path do
  libs_on_github.each do |u|
    system("git clone #{u}")
  end
end
